name: Build and deploy JAR app to Azure Web App

env:
  JAVA_VERSION: '17'
  DISTRIBUTION: zulu

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        environment: [dev, qualif, prod]

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app

      - name: Set environment variables
        #run: echo "AZURE_WEBAPP_NAME=${{ secrets['AZURE_WEBAPP_NAME_' + matrix.environment | toUpperCase()] }}" >> $GITHUB_ENV
              #echo "AZURE_WEBAPP_PUBLISH_PROFILE=${{ secrets['AZURE_WEBAPP_PUBLISH_PROFILE_' + matrix.environment | toUpperCase()] }}" >> $GITHUB_ENV

        run: echo "AZURE_WEBAPP_NAME_DEV" >> $GITHUB_ENV
              echo "AZURE_WEBAPP_PUBLISH_PROFILE_DEV" >> $GITHUB_ENV

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_DEV }}
          publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE_DEV }}
          package: '*.jar'
